language: generic
dist: xenial
sudo: required

matrix:
  fast_finish: true
  include:
    - env:
      - TARGET=xenial_x64
    - env:
      - TARGET=bionic_x64
    - env:
      - TARGET=xenial_armhf
      if: type != pull_request
    - env:
      - TARGET=xenial_arm64
      if: type != pull_request
    - env:
      - TARGET=bionic_armhf
      if: type != pull_request
    - env:
      - TARGET=bionic_arm64
      if: type != pull_request

services:
- docker

before_script: cd ..
script:
- echo "Triggered from PR - $TRAVIS_PULL_REQUEST"
- whoami
- pwd
- ls -la
- chmod 777 $PWD
- chmod 777 $PWD/nugu-linux
- docker run -t --rm --privileged -v $PWD:$PWD -w $PWD/nugu-linux -v /var/lib/schroot/chroots
  nugulinux/buildenv:$TARGET sdkbuild.sh
- ls -l
- mkdir /tmp/result
- cp *.deb /tmp/result/

deploy:
  provider: releases
  api_key:
    secure: LkNwnmUuywy8ZkNkYV/yk2rLRDH5UwScyUh1yIxNoQ+WiL62INr9G8VNbMk59XbsVDHtIDH/FycYPQmOjIHVwp4cn4Ffk3Yx7bRXAoS/xbQhkNXj42ZBGiuxQOZg+F3CIv3HYdC4+s5HkKK/2tNBgs+zU7bNH0xK3MbU9H7WvyD8AlAsIZ80p1v0aByquR+c3z7jlPKxwvOWOJlBgjhajQMr5Y/RkQPZXKUH3y6wue9gUcxp/RduQt4UkMkQLh96gMf+9MEaiLf+6MTW2vZmcNt3Z/N8YSueIMAbvFURpkePqCXd1mgUi0JKrSXu67jQwkFd+fhbagzVA8R9D/DD3d6fZlS1SLpGWZb3UIbxOOA4ExLkWtSdp9tfGMrgfH2oRthZnmoKZmOBh/LDbrI30nfHXjfqh/RL+CPuyYYkNBVcxXfwyXUdJJlk+5fgOtSY5nyiQqMHg08q5jGgaDrwxNTLtq6Xz2vp9eEuG/++RD436WGTaSoMAeJNWxarczQmSbxhlCBmhOnOZod+flDJRAXyWo8iqOrski5+KX/4SMnavBhhfI6tfIfdQnznZFWNU0yFy7RqG//B3cTi8F7BLsI/5Rwa0f9IW5tq7aarHb8ymrHwRneq2HWvBBjo5/d3e93oaMB4IfBac2EJPtXh+VtRRrFkjhPOB0UUboYGpuw=
  file_glob: true
  file: /tmp/result/*.deb
  skip_cleanup: true
  on:
    repo: nugu-developers/nugu-linux
    tags: true
