var annotated_dup =
[
    [ "NuguCapability", null, [
      [ "ASRAttribute", "structNuguCapability_1_1ASRAttribute.html", "structNuguCapability_1_1ASRAttribute" ],
      [ "CapabilityFactory", "classNuguCapability_1_1CapabilityFactory.html", "classNuguCapability_1_1CapabilityFactory" ],
      [ "IASRHandler", "classNuguCapability_1_1IASRHandler.html", "classNuguCapability_1_1IASRHandler" ],
      [ "IASRListener", "classNuguCapability_1_1IASRListener.html", "classNuguCapability_1_1IASRListener" ],
      [ "IAudioPlayerHandler", "classNuguCapability_1_1IAudioPlayerHandler.html", "classNuguCapability_1_1IAudioPlayerHandler" ],
      [ "IAudioPlayerListener", "classNuguCapability_1_1IAudioPlayerListener.html", "classNuguCapability_1_1IAudioPlayerListener" ],
      [ "IMicHandler", "classNuguCapability_1_1IMicHandler.html", "classNuguCapability_1_1IMicHandler" ],
      [ "IMicListener", "classNuguCapability_1_1IMicListener.html", "classNuguCapability_1_1IMicListener" ],
      [ "ISpeakerHandler", "classNuguCapability_1_1ISpeakerHandler.html", "classNuguCapability_1_1ISpeakerHandler" ],
      [ "ISpeakerListener", "classNuguCapability_1_1ISpeakerListener.html", "classNuguCapability_1_1ISpeakerListener" ],
      [ "ISystemHandler", "classNuguCapability_1_1ISystemHandler.html", "classNuguCapability_1_1ISystemHandler" ],
      [ "ISystemListener", "classNuguCapability_1_1ISystemListener.html", "classNuguCapability_1_1ISystemListener" ],
      [ "ITextHandler", "classNuguCapability_1_1ITextHandler.html", "classNuguCapability_1_1ITextHandler" ],
      [ "ITextListener", "classNuguCapability_1_1ITextListener.html", "classNuguCapability_1_1ITextListener" ],
      [ "ITTSHandler", "classNuguCapability_1_1ITTSHandler.html", "classNuguCapability_1_1ITTSHandler" ],
      [ "ITTSListener", "classNuguCapability_1_1ITTSListener.html", "classNuguCapability_1_1ITTSListener" ],
      [ "SpeakerInfo", "classNuguCapability_1_1SpeakerInfo.html", "classNuguCapability_1_1SpeakerInfo" ],
      [ "TextAttribute", "structNuguCapability_1_1TextAttribute.html", "structNuguCapability_1_1TextAttribute" ],
      [ "TTSAttribute", "structNuguCapability_1_1TTSAttribute.html", "structNuguCapability_1_1TTSAttribute" ]
    ] ],
    [ "NuguClientKit", null, [
      [ "Capability", "classNuguClientKit_1_1Capability.html", "classNuguClientKit_1_1Capability" ],
      [ "CapabilityEvent", "classNuguClientKit_1_1CapabilityEvent.html", "classNuguClientKit_1_1CapabilityEvent" ],
      [ "ICapabilityHelper", "classNuguClientKit_1_1ICapabilityHelper.html", "classNuguClientKit_1_1ICapabilityHelper" ],
      [ "ICapabilityInterface", "classNuguClientKit_1_1ICapabilityInterface.html", "classNuguClientKit_1_1ICapabilityInterface" ],
      [ "ICapabilityListener", "classNuguClientKit_1_1ICapabilityListener.html", "classNuguClientKit_1_1ICapabilityListener" ],
      [ "IFocusListener", "classNuguClientKit_1_1IFocusListener.html", "classNuguClientKit_1_1IFocusListener" ],
      [ "IMediaPlayer", "classNuguClientKit_1_1IMediaPlayer.html", "classNuguClientKit_1_1IMediaPlayer" ],
      [ "IMediaPlayerListener", "classNuguClientKit_1_1IMediaPlayerListener.html", "classNuguClientKit_1_1IMediaPlayerListener" ],
      [ "INetworkManager", "classNuguClientKit_1_1INetworkManager.html", "classNuguClientKit_1_1INetworkManager" ],
      [ "INetworkManagerListener", "classNuguClientKit_1_1INetworkManagerListener.html", "classNuguClientKit_1_1INetworkManagerListener" ],
      [ "INuguClientListener", "classNuguClientKit_1_1INuguClientListener.html", "classNuguClientKit_1_1INuguClientListener" ],
      [ "INuguCoreContainer", "classNuguClientKit_1_1INuguCoreContainer.html", "classNuguClientKit_1_1INuguCoreContainer" ],
      [ "INuguTimer", "classNuguClientKit_1_1INuguTimer.html", "classNuguClientKit_1_1INuguTimer" ],
      [ "IPlaySyncManager", "classNuguClientKit_1_1IPlaySyncManager.html", "classNuguClientKit_1_1IPlaySyncManager" ],
      [ "IPlaySyncManagerListener", "classNuguClientKit_1_1IPlaySyncManagerListener.html", "classNuguClientKit_1_1IPlaySyncManagerListener" ],
      [ "ISpeechRecognizer", "classNuguClientKit_1_1ISpeechRecognizer.html", "classNuguClientKit_1_1ISpeechRecognizer" ],
      [ "ISpeechRecognizerListener", "classNuguClientKit_1_1ISpeechRecognizerListener.html", "classNuguClientKit_1_1ISpeechRecognizerListener" ],
      [ "ITTSPlayer", "classNuguClientKit_1_1ITTSPlayer.html", "classNuguClientKit_1_1ITTSPlayer" ],
      [ "IWakeupHandler", "classNuguClientKit_1_1IWakeupHandler.html", "classNuguClientKit_1_1IWakeupHandler" ],
      [ "IWakeupListener", "classNuguClientKit_1_1IWakeupListener.html", "classNuguClientKit_1_1IWakeupListener" ],
      [ "NuguClient", "classNuguClientKit_1_1NuguClient.html", "classNuguClientKit_1_1NuguClient" ]
    ] ],
    [ "nugu_audio_property", "structnugu__audio__property.html", "structnugu__audio__property" ],
    [ "nugu_decoder_driver_ops", "structnugu__decoder__driver__ops.html", "structnugu__decoder__driver__ops" ],
    [ "nugu_network_server_policy", "structnugu__network__server__policy.html", "structnugu__network__server__policy" ],
    [ "nugu_pcm_driver_ops", "structnugu__pcm__driver__ops.html", "structnugu__pcm__driver__ops" ],
    [ "nugu_player_driver_ops", "structnugu__player__driver__ops.html", "structnugu__player__driver__ops" ],
    [ "nugu_plugin_desc", "structnugu__plugin__desc.html", "structnugu__plugin__desc" ],
    [ "nugu_recorder_driver_ops", "structnugu__recorder__driver__ops.html", "structnugu__recorder__driver__ops" ]
];