var files =
[
    [ "asr_interface.hh", "asr__interface_8hh.html", "asr__interface_8hh" ],
    [ "audio_player_interface.hh", "audio__player__interface_8hh.html", "audio__player__interface_8hh" ],
    [ "capability.hh", "capability_8hh.html", null ],
    [ "capability_factory.hh", "capability__factory_8hh.html", null ],
    [ "capability_helper_interface.hh", "capability__helper__interface_8hh.html", null ],
    [ "capability_interface.hh", "capability__interface_8hh.html", null ],
    [ "media_player_interface.hh", "media__player__interface_8hh.html", "media__player__interface_8hh" ],
    [ "mic_interface.hh", "mic__interface_8hh.html", "mic__interface_8hh" ],
    [ "network_manager_interface.hh", "network__manager__interface_8hh.html", "network__manager__interface_8hh" ],
    [ "nugu_audio.h", "nugu__audio_8h.html", "nugu__audio_8h" ],
    [ "nugu_buffer.h", "nugu__buffer_8h.html", "nugu__buffer_8h" ],
    [ "nugu_client.hh", "nugu__client_8hh.html", [
      [ "CapabilityBuilder", "classNuguClientKit_1_1NuguClient_1_1CapabilityBuilder.html", "classNuguClientKit_1_1NuguClient_1_1CapabilityBuilder" ]
    ] ],
    [ "nugu_client_listener.hh", "nugu__client__listener_8hh.html", null ],
    [ "nugu_core_container_interface.hh", "nugu__core__container__interface_8hh.html", null ],
    [ "nugu_decoder.h", "nugu__decoder_8h.html", "nugu__decoder_8h" ],
    [ "nugu_directive.h", "nugu__directive_8h.html", "nugu__directive_8h" ],
    [ "nugu_directive_sequencer.h", "nugu__directive__sequencer_8h.html", "nugu__directive__sequencer_8h" ],
    [ "nugu_equeue.h", "nugu__equeue_8h.html", "nugu__equeue_8h" ],
    [ "nugu_event.h", "nugu__event_8h.html", "nugu__event_8h" ],
    [ "nugu_focus.h", "nugu__focus_8h.html", "nugu__focus_8h" ],
    [ "nugu_log.h", "nugu__log_8h.html", "nugu__log_8h" ],
    [ "nugu_media.h", "nugu__media_8h.html", "nugu__media_8h" ],
    [ "nugu_network_manager.h", "nugu__network__manager_8h.html", "nugu__network__manager_8h" ],
    [ "nugu_pcm.h", "nugu__pcm_8h.html", "nugu__pcm_8h" ],
    [ "nugu_player.h", "nugu__player_8h.html", "nugu__player_8h" ],
    [ "nugu_plugin.h", "nugu__plugin_8h.html", "nugu__plugin_8h" ],
    [ "nugu_recorder.h", "nugu__recorder_8h.html", "nugu__recorder_8h" ],
    [ "nugu_ringbuffer.h", "nugu__ringbuffer_8h.html", "nugu__ringbuffer_8h" ],
    [ "nugu_timer.h", "nugu__timer_8h.html", "nugu__timer_8h" ],
    [ "nugu_timer_interface.hh", "nugu__timer__interface_8hh.html", "nugu__timer__interface_8hh" ],
    [ "nugu_uuid.h", "nugu__uuid_8h.html", "nugu__uuid_8h" ],
    [ "playsync_manager_interface.hh", "playsync__manager__interface_8hh.html", [
      [ "DisplayRenderer", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderer.html", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderer" ],
      [ "DisplayRenderInfo", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderInfo.html", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderInfo" ]
    ] ],
    [ "speaker_interface.hh", "speaker__interface_8hh.html", "speaker__interface_8hh" ],
    [ "speech_recognizer_interface.hh", "speech__recognizer__interface_8hh.html", "speech__recognizer__interface_8hh" ],
    [ "system_interface.hh", "system__interface_8hh.html", "system__interface_8hh" ],
    [ "text_interface.hh", "text__interface_8hh.html", "text__interface_8hh" ],
    [ "tts_interface.hh", "tts__interface_8hh.html", "tts__interface_8hh" ],
    [ "wakeup_interface.hh", "wakeup__interface_8hh.html", "wakeup__interface_8hh" ]
];