var hierarchy =
[
    [ "NuguCapability::ASRAttribute", "structNuguCapability_1_1ASRAttribute.html", null ],
    [ "NuguClientKit::NuguClient::CapabilityBuilder", "classNuguClientKit_1_1NuguClient_1_1CapabilityBuilder.html", null ],
    [ "NuguClientKit::CapabilityEvent", "classNuguClientKit_1_1CapabilityEvent.html", null ],
    [ "NuguCapability::CapabilityFactory", "classNuguCapability_1_1CapabilityFactory.html", null ],
    [ "NuguClientKit::IPlaySyncManager::DisplayRenderer", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderer.html", null ],
    [ "NuguClientKit::IPlaySyncManager::DisplayRenderInfo", "structNuguClientKit_1_1IPlaySyncManager_1_1DisplayRenderInfo.html", null ],
    [ "NuguClientKit::ICapabilityHelper", "classNuguClientKit_1_1ICapabilityHelper.html", null ],
    [ "NuguClientKit::ICapabilityInterface", "classNuguClientKit_1_1ICapabilityInterface.html", [
      [ "NuguCapability::IASRHandler", "classNuguCapability_1_1IASRHandler.html", null ],
      [ "NuguCapability::IAudioPlayerHandler", "classNuguCapability_1_1IAudioPlayerHandler.html", null ],
      [ "NuguCapability::IMicHandler", "classNuguCapability_1_1IMicHandler.html", null ],
      [ "NuguCapability::ISpeakerHandler", "classNuguCapability_1_1ISpeakerHandler.html", null ],
      [ "NuguCapability::ISystemHandler", "classNuguCapability_1_1ISystemHandler.html", null ],
      [ "NuguCapability::ITextHandler", "classNuguCapability_1_1ITextHandler.html", null ],
      [ "NuguCapability::ITTSHandler", "classNuguCapability_1_1ITTSHandler.html", null ],
      [ "NuguClientKit::Capability", "classNuguClientKit_1_1Capability.html", null ]
    ] ],
    [ "NuguClientKit::ICapabilityListener", "classNuguClientKit_1_1ICapabilityListener.html", [
      [ "NuguCapability::IASRListener", "classNuguCapability_1_1IASRListener.html", null ],
      [ "NuguCapability::IAudioPlayerListener", "classNuguCapability_1_1IAudioPlayerListener.html", null ],
      [ "NuguCapability::IMicListener", "classNuguCapability_1_1IMicListener.html", null ],
      [ "NuguCapability::ISpeakerListener", "classNuguCapability_1_1ISpeakerListener.html", null ],
      [ "NuguCapability::ISystemListener", "classNuguCapability_1_1ISystemListener.html", null ],
      [ "NuguCapability::ITextListener", "classNuguCapability_1_1ITextListener.html", null ],
      [ "NuguCapability::ITTSListener", "classNuguCapability_1_1ITTSListener.html", null ]
    ] ],
    [ "NuguClientKit::IFocusListener", "classNuguClientKit_1_1IFocusListener.html", null ],
    [ "NuguClientKit::IMediaPlayer", "classNuguClientKit_1_1IMediaPlayer.html", [
      [ "NuguClientKit::ITTSPlayer", "classNuguClientKit_1_1ITTSPlayer.html", null ]
    ] ],
    [ "NuguClientKit::IMediaPlayerListener", "classNuguClientKit_1_1IMediaPlayerListener.html", null ],
    [ "NuguClientKit::INetworkManager", "classNuguClientKit_1_1INetworkManager.html", null ],
    [ "NuguClientKit::INetworkManagerListener", "classNuguClientKit_1_1INetworkManagerListener.html", null ],
    [ "NuguClientKit::INuguClientListener", "classNuguClientKit_1_1INuguClientListener.html", null ],
    [ "NuguClientKit::INuguCoreContainer", "classNuguClientKit_1_1INuguCoreContainer.html", null ],
    [ "NuguClientKit::INuguTimer", "classNuguClientKit_1_1INuguTimer.html", null ],
    [ "NuguClientKit::IPlaySyncManager", "classNuguClientKit_1_1IPlaySyncManager.html", null ],
    [ "NuguClientKit::IPlaySyncManagerListener", "classNuguClientKit_1_1IPlaySyncManagerListener.html", null ],
    [ "NuguClientKit::ISpeechRecognizer", "classNuguClientKit_1_1ISpeechRecognizer.html", null ],
    [ "NuguClientKit::ISpeechRecognizerListener", "classNuguClientKit_1_1ISpeechRecognizerListener.html", null ],
    [ "NuguClientKit::IWakeupHandler", "classNuguClientKit_1_1IWakeupHandler.html", null ],
    [ "NuguClientKit::IWakeupListener", "classNuguClientKit_1_1IWakeupListener.html", null ],
    [ "nugu_audio_property", "structnugu__audio__property.html", null ],
    [ "nugu_decoder_driver_ops", "structnugu__decoder__driver__ops.html", null ],
    [ "nugu_network_server_policy", "structnugu__network__server__policy.html", null ],
    [ "nugu_pcm_driver_ops", "structnugu__pcm__driver__ops.html", null ],
    [ "nugu_player_driver_ops", "structnugu__player__driver__ops.html", null ],
    [ "nugu_plugin_desc", "structnugu__plugin__desc.html", null ],
    [ "nugu_recorder_driver_ops", "structnugu__recorder__driver__ops.html", null ],
    [ "NuguClientKit::NuguClient", "classNuguClientKit_1_1NuguClient.html", null ],
    [ "NuguCapability::SpeakerInfo", "classNuguCapability_1_1SpeakerInfo.html", null ],
    [ "NuguCapability::TextAttribute", "structNuguCapability_1_1TextAttribute.html", null ],
    [ "NuguCapability::TTSAttribute", "structNuguCapability_1_1TTSAttribute.html", null ]
];