var hierarchy =
[
    [ "NuguCapability::_ASRAttribute", "structNuguCapability_1_1__ASRAttribute.html", null ],
    [ "NuguCapability::_BatteryInfo", "structNuguCapability_1_1__BatteryInfo.html", null ],
    [ "NuguClientKit::_BlockingPolicy", "structNuguClientKit_1_1__BlockingPolicy.html", null ],
    [ "NuguCapability::_BTDeviceInfo", "structNuguCapability_1_1__BTDeviceInfo.html", null ],
    [ "NuguCapability::_BTProfile", "structNuguCapability_1_1__BTProfile.html", null ],
    [ "NuguCapability::_ChipsInfo", "structNuguCapability_1_1__ChipsInfo.html", null ],
    [ "NuguClientKit::_DirectiveCancelPolicy", "structNuguClientKit_1_1__DirectiveCancelPolicy.html", null ],
    [ "NuguCapability::_DisplayContextInfo", "structNuguCapability_1_1__DisplayContextInfo.html", null ],
    [ "NuguClientKit::_EpdAttribute", "structNuguClientKit_1_1__EpdAttribute.html", null ],
    [ "NuguClientKit::_FocusConfiguration", "structNuguClientKit_1_1__FocusConfiguration.html", null ],
    [ "NuguCapability::_LocationInfo", "structNuguCapability_1_1__LocationInfo.html", null ],
    [ "_nugu_http_response", "struct__nugu__http__response.html", null ],
    [ "NuguClientKit::_RecognitionResult", "structNuguClientKit_1_1__RecognitionResult.html", null ],
    [ "NuguClientKit::_Session", "structNuguClientKit_1_1__Session.html", null ],
    [ "NuguCapability::_TextAttribute", "structNuguCapability_1_1__TextAttribute.html", null ],
    [ "NuguCapability::_TTSAttribute", "structNuguCapability_1_1__TTSAttribute.html", null ],
    [ "NuguClientKit::_WakeupModelFile", "structNuguClientKit_1_1__WakeupModelFile.html", null ],
    [ "NuguClientKit::AuthResponse", "structNuguClientKit_1_1AuthResponse.html", null ],
    [ "NuguClientKit::NuguClient::CapabilityBuilder", "classNuguClientKit_1_1NuguClient_1_1CapabilityBuilder.html", null ],
    [ "NuguClientKit::CapabilityEvent", "classNuguClientKit_1_1CapabilityEvent.html", null ],
    [ "NuguCapability::CapabilityFactory", "classNuguCapability_1_1CapabilityFactory.html", null ],
    [ "NuguCapability::_ChipsInfo::Content", "structNuguCapability_1_1__ChipsInfo_1_1Content.html", null ],
    [ "NuguClientKit::ICapabilityHelper", "classNuguClientKit_1_1ICapabilityHelper.html", null ],
    [ "NuguClientKit::ICapabilityInterface", "classNuguClientKit_1_1ICapabilityInterface.html", [
      [ "NuguCapability::IASRHandler", "classNuguCapability_1_1IASRHandler.html", null ],
      [ "NuguCapability::IAudioPlayerHandler", "classNuguCapability_1_1IAudioPlayerHandler.html", null ],
      [ "NuguCapability::IBatteryHandler", "classNuguCapability_1_1IBatteryHandler.html", null ],
      [ "NuguCapability::IBluetoothHandler", "classNuguCapability_1_1IBluetoothHandler.html", null ],
      [ "NuguCapability::IChipsHandler", "classNuguCapability_1_1IChipsHandler.html", null ],
      [ "NuguCapability::IDisplayHandler", "classNuguCapability_1_1IDisplayHandler.html", [
        [ "NuguCapability::IAudioPlayerHandler", "classNuguCapability_1_1IAudioPlayerHandler.html", null ]
      ] ],
      [ "NuguCapability::IExtensionHandler", "classNuguCapability_1_1IExtensionHandler.html", null ],
      [ "NuguCapability::ILocationHandler", "classNuguCapability_1_1ILocationHandler.html", null ],
      [ "NuguCapability::IMessageHandler", "classNuguCapability_1_1IMessageHandler.html", null ],
      [ "NuguCapability::IMicHandler", "classNuguCapability_1_1IMicHandler.html", null ],
      [ "NuguCapability::INudgeHandler", "classNuguCapability_1_1INudgeHandler.html", null ],
      [ "NuguCapability::IPhoneCallHandler", "classNuguCapability_1_1IPhoneCallHandler.html", null ],
      [ "NuguCapability::IRoutineHandler", "classNuguCapability_1_1IRoutineHandler.html", null ],
      [ "NuguCapability::ISessionHandler", "classNuguCapability_1_1ISessionHandler.html", null ],
      [ "NuguCapability::ISoundHandler", "classNuguCapability_1_1ISoundHandler.html", null ],
      [ "NuguCapability::ISpeakerHandler", "classNuguCapability_1_1ISpeakerHandler.html", null ],
      [ "NuguCapability::ISystemHandler", "classNuguCapability_1_1ISystemHandler.html", null ],
      [ "NuguCapability::ITTSHandler", "classNuguCapability_1_1ITTSHandler.html", null ],
      [ "NuguCapability::ITextHandler", "classNuguCapability_1_1ITextHandler.html", null ],
      [ "NuguCapability::IUtilityHandler", "classNuguCapability_1_1IUtilityHandler.html", null ],
      [ "NuguClientKit::Capability", "classNuguClientKit_1_1Capability.html", null ]
    ] ],
    [ "NuguClientKit::ICapabilityListener", "classNuguClientKit_1_1ICapabilityListener.html", [
      [ "NuguCapability::IASRListener", "classNuguCapability_1_1IASRListener.html", null ],
      [ "NuguCapability::IAudioPlayerListener", "classNuguCapability_1_1IAudioPlayerListener.html", null ],
      [ "NuguCapability::IBatteryListener", "classNuguCapability_1_1IBatteryListener.html", null ],
      [ "NuguCapability::IBluetoothListener", "classNuguCapability_1_1IBluetoothListener.html", null ],
      [ "NuguCapability::IChipsListener", "classNuguCapability_1_1IChipsListener.html", null ],
      [ "NuguCapability::IDisplayListener", "classNuguCapability_1_1IDisplayListener.html", [
        [ "NuguCapability::IAudioPlayerDisplayListener", "classNuguCapability_1_1IAudioPlayerDisplayListener.html", null ]
      ] ],
      [ "NuguCapability::IExtensionListener", "classNuguCapability_1_1IExtensionListener.html", null ],
      [ "NuguCapability::ILocationListener", "classNuguCapability_1_1ILocationListener.html", null ],
      [ "NuguCapability::IMessageListener", "classNuguCapability_1_1IMessageListener.html", null ],
      [ "NuguCapability::IMicListener", "classNuguCapability_1_1IMicListener.html", null ],
      [ "NuguCapability::INudgeListener", "classNuguCapability_1_1INudgeListener.html", null ],
      [ "NuguCapability::IPhoneCallListener", "classNuguCapability_1_1IPhoneCallListener.html", null ],
      [ "NuguCapability::IRoutineListener", "classNuguCapability_1_1IRoutineListener.html", null ],
      [ "NuguCapability::ISessionListener", "classNuguCapability_1_1ISessionListener.html", null ],
      [ "NuguCapability::ISoundListener", "classNuguCapability_1_1ISoundListener.html", null ],
      [ "NuguCapability::ISpeakerListener", "classNuguCapability_1_1ISpeakerListener.html", null ],
      [ "NuguCapability::ISystemListener", "classNuguCapability_1_1ISystemListener.html", null ],
      [ "NuguCapability::ITTSListener", "classNuguCapability_1_1ITTSListener.html", null ],
      [ "NuguCapability::ITextListener", "classNuguCapability_1_1ITextListener.html", null ],
      [ "NuguCapability::IUtilityListener", "classNuguCapability_1_1IUtilityListener.html", null ]
    ] ],
    [ "NuguClientKit::IDialogUXStateAggregatorListener", "classNuguClientKit_1_1IDialogUXStateAggregatorListener.html", null ],
    [ "NuguClientKit::IDirectiveSequencer", "classNuguClientKit_1_1IDirectiveSequencer.html", null ],
    [ "NuguClientKit::IDirectiveSequencerListener", "classNuguClientKit_1_1IDirectiveSequencerListener.html", null ],
    [ "NuguClientKit::IFocusManager", "classNuguClientKit_1_1IFocusManager.html", null ],
    [ "NuguClientKit::IFocusManagerObserver", "classNuguClientKit_1_1IFocusManagerObserver.html", null ],
    [ "NuguClientKit::IFocusResourceListener", "classNuguClientKit_1_1IFocusResourceListener.html", null ],
    [ "NuguClientKit::IInteractionControlManager", "classNuguClientKit_1_1IInteractionControlManager.html", null ],
    [ "NuguClientKit::IInteractionControlManagerListener", "classNuguClientKit_1_1IInteractionControlManagerListener.html", null ],
    [ "NuguClientKit::IMediaPlayer", "classNuguClientKit_1_1IMediaPlayer.html", [
      [ "NuguClientKit::ITTSPlayer", "classNuguClientKit_1_1ITTSPlayer.html", null ]
    ] ],
    [ "NuguClientKit::IMediaPlayerListener", "classNuguClientKit_1_1IMediaPlayerListener.html", null ],
    [ "NuguClientKit::INetworkManager", "classNuguClientKit_1_1INetworkManager.html", null ],
    [ "NuguClientKit::INetworkManagerListener", "classNuguClientKit_1_1INetworkManagerListener.html", null ],
    [ "NuguClientKit::INuguCoreContainer", "classNuguClientKit_1_1INuguCoreContainer.html", null ],
    [ "NuguClientKit::INuguTimer", "classNuguClientKit_1_1INuguTimer.html", null ],
    [ "NuguClientKit::IPlaySyncManager", "classNuguClientKit_1_1IPlaySyncManager.html", null ],
    [ "NuguClientKit::IPlaySyncManagerListener", "classNuguClientKit_1_1IPlaySyncManagerListener.html", null ],
    [ "NuguClientKit::IRoutineManager", "classNuguClientKit_1_1IRoutineManager.html", null ],
    [ "NuguClientKit::IRoutineManagerListener", "classNuguClientKit_1_1IRoutineManagerListener.html", null ],
    [ "NuguClientKit::ISessionManager", "classNuguClientKit_1_1ISessionManager.html", null ],
    [ "NuguClientKit::ISessionManagerListener", "classNuguClientKit_1_1ISessionManagerListener.html", null ],
    [ "NuguClientKit::ISpeechRecognizer", "classNuguClientKit_1_1ISpeechRecognizer.html", null ],
    [ "NuguClientKit::ISpeechRecognizerAggregator", "classNuguClientKit_1_1ISpeechRecognizerAggregator.html", null ],
    [ "NuguClientKit::ISpeechRecognizerAggregatorListener", "classNuguClientKit_1_1ISpeechRecognizerAggregatorListener.html", null ],
    [ "NuguClientKit::ISpeechRecognizerListener", "classNuguClientKit_1_1ISpeechRecognizerListener.html", null ],
    [ "NuguClientKit::IWakeupHandler", "classNuguClientKit_1_1IWakeupHandler.html", null ],
    [ "NuguClientKit::IWakeupListener", "classNuguClientKit_1_1IWakeupListener.html", null ],
    [ "nugu_audio_property", "structnugu__audio__property.html", null ],
    [ "nugu_decoder_driver_ops", "structnugu__decoder__driver__ops.html", null ],
    [ "nugu_encoder_driver_ops", "structnugu__encoder__driver__ops.html", null ],
    [ "nugu_network_server_policy", "structnugu__network__server__policy.html", null ],
    [ "nugu_pcm_driver_ops", "structnugu__pcm__driver__ops.html", null ],
    [ "nugu_player_driver_ops", "structnugu__player__driver__ops.html", null ],
    [ "nugu_plugin_desc", "structnugu__plugin__desc.html", null ],
    [ "nugu_prof_data", "structnugu__prof__data.html", null ],
    [ "nugu_recorder_driver_ops", "structnugu__recorder__driver__ops.html", null ],
    [ "NuguClientKit::NuguAuth", "classNuguClientKit_1_1NuguAuth.html", null ],
    [ "NuguClientKit::NuguClient", "classNuguClientKit_1_1NuguClient.html", null ],
    [ "NuguClientKit::NuguDeviceConfig", "structNuguClientKit_1_1NuguDeviceConfig.html", null ],
    [ "NuguClientKit::NuguHttpRest", "classNuguClientKit_1_1NuguHttpRest.html", null ],
    [ "NuguClientKit::NuguRunner", "classNuguClientKit_1_1NuguRunner.html", null ],
    [ "NuguClientKit::NuguToken", "structNuguClientKit_1_1NuguToken.html", null ],
    [ "NuguCapability::SpeakerInfo", "classNuguCapability_1_1SpeakerInfo.html", null ]
];