name: MacOS
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: false
        default: ''

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Comment
        run: echo "Comment - ${{ github.event.inputs.comment }}"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Homebrew setup
        run: brew install cmake jsoncpp curl openssl gstreamer gst-plugins-base pkg-config

      - name: Build
        run: |
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@3/lib/pkgconfig"

          mkdir build && cd build
          cmake .. -DENABLE_VENDOR_LIBRARY=OFF
          make -j3
          make test
          DESTDIR=tmp make install
